version: "3"
services:
  webhosting:
    container_name: "webhosting"
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - ./nginx/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
